/**
 * 
 */
 
 var stations = [{
        "name": "100FM שידור חי",
        "audio": "http://gb25.streamgates.net/radios-audio/100fmAudio/playlist.m3u8",
        "audioA": "http://gb25.streamgates.net/radios-audio/100fmAudio/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch0-100fm.xml",
        "slug": "100fm",
        "logo": "http://digital.100fm.co.il/app/images2/100fmlive.png",
        "cover": "http://digital.100fm.co.il/app/cover/100fm.png",
        "color": "#F8F301",
        "description": "השידור החי של רדיוס 100fm\nתחנת המוזיקה המואזנת בישראל\nהאזנה נעימה"
    },
    {
        "name": "100% Hits",
        "audio": "http://gb25.streamgates.net/radios-audio/100Hits/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Hits/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch1-Hits.xml",
        "slug": "hits",
        "logo": "http://digital.100fm.co.il/app/images2/hits.png",
        "cover": "http://digital.100fm.co.il/app/cover/hits.png",
        "color": "#f44336",
        "description": "עוד להיט מאילנית! \"אוהבים להיטים?\"\nזה הערוץ שלכם!\nלהיטים מובילים בהשראת התוכנית\n\"Select\" עם הדר תדמור."
    },
    {
        "name": "100% שלמה ארצי",
        "audio": "http://gb25.streamgates.net/radios-audio/100Shlomo/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Shlomo/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch33-Shlomo.xml",
        "slug": "shlomo",
        "logo": "http://digital.100fm.co.il/app/images2/shlomo.png",
        "cover": "http://digital.100fm.co.il/app/cover/shlomo.png",
        "color": "#f44336",
        "description": "מאה השירים הגדולים ששלמה ארצי מכל הזמנים עכשיו רק ברדיוס 100FM"
    },
	{
        "name": "100% Top40",
        "audio": "http://gb25.streamgates.net/radios-audio/100Top40/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Top40/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch7-Top40.xml",
        "slug": "top40",
        "logo": "http://digital.100fm.co.il/app/images2/top40.png",
        "cover": "http://digital.100fm.co.il/app/cover/top40.png",
        "color": "#009688",
        "description": "חייבים לדעת בכל רגע נתון מה ה40 השירים\nהכי פופלריים?... יש רופאים שמטפלים בזה ☺\nאבל בינתיים – זה הערוץ שלכם!\n100% Top40, הלהיטים הגדולים ששולטים\nבכל המצעדים."
    },
    {
        "name": "100% Workout",
        "audio": "http://gb25.streamgates.net/radios-audio/100Workout/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Workout/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch24-Workout.xml",
        "slug": "workout",
        "logo": "http://digital.100fm.co.il/app/images2/workout.png",
        "cover": "http://digital.100fm.co.il/app/cover/workout.png",
        "color": "#607d8b",
        "description": "לוקחים הכל ברוח ספורטיבית? פותחים את\nהבוקר עם 200 שכיבות שמיכה ונרגעים רק\nשאתם תלויים על רצועות TRX? זה הערוץ\nשלכם! 100% Workout שירים לרוץ איתם"
    },
	{
        "name": "100% Dance",
        "audio": "http://gb25.streamgates.net/radios-audio/100Dance/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Dance/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch6-Dance.xml",
        "slug": "dance",
        "logo": "http://digital.100fm.co.il/app/images2/dance.png",
        "cover": "http://digital.100fm.co.il/app/cover/dance.png",
        "color": "#03a9f4",
        "description": "רק רוצים לרקוד ואין למה? אז עכשיו יש!\n100% Dance להיטי הדאנס הגדולים מכל\nהזמנים."
    },
	{
        "name": "100% Stand-up",
        "audio": "http://gb25.streamgates.net/radios-audio/100StandUp/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100StandUp/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch32-Standup.xml",
        "slug": "standup",
        "logo": "http://digital.100fm.co.il/app/images2/standup.png",
        "cover": "http://digital.100fm.co.il/app/cover/standup.png",
        "color": "#03a9f4",
        "description": "רק רוצים לרקוד ואין למה? אז עכשיו יש!\n100% Dance להיטי הדאנס הגדולים מכל\nהזמנים.",
		"sort":"1"
    },
	{
        "name": "100% Retro",
        "audio": "http://gb25.streamgates.net/radios-audio/100Retro/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Retro/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch2-Retro.xml",
        "slug": "retro",
        "logo": "http://digital.100fm.co.il/app/images2/retro.png",
        "cover": "http://digital.100fm.co.il/app/cover/retro.png",
        "color": "#673ab7",
        "description": "עדיין משתמשים בפקס? נגמרו לכם הבטריות\nבווקמן? זה הערוץ בשבילכם!\nהלהיטים הגדולים ברוח התוכנית \"מנהרת\nהזמן\" עם ירון אשבל."
    },
	{
        "name": "100% Brit Pop",
        "audio": "http://gb25.streamgates.net/radios-audio/100Britpop/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Britpop/icecast.audio",
        "info": "http://100fm.xml.multix.co.il/xml/100britpop.xml",
        "slug": "britpop",
        "logo": "http://digital.100fm.co.il/app/images2/britpop.png",
        "cover": "http://digital.100fm.co.il/app/cover/britpop.png",
        "color": "#673ab7",
        "description": "לכל מי שעדיין שותה את התה שלו בארבע אחר הצהריים - ערוץ הבריט פופ, כל הלהיטים ישר מבריטניה"
    },
	{
        "name": "100% 90's",
        "audio": "http://gb25.streamgates.net/radios-audio/10090s/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/10090s/icecast.audio",
        "info": "http://digital.100fm.co.il/label/Ch13-90s.xml",
        "slug": "s90",
        "logo": "http://digital.100fm.co.il/app/images2/s90.png",
        "cover": "http://digital.100fm.co.il/app/cover/s90.png",
        "color": "#4caf50",
        "description": "עדיין מחכים שהתמונות יחזרו מפיתוח?\nנשארו לכם 20 דקות בTalkman?\nזה הערוץ שלכם!\nהלהיטים ה\"גזעיים\" של שנות ה90."
    },
    {
        "name": "100% 80's",
        "audio": "http://gb25.streamgates.net/radios-audio/10080s/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/10080s/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch21-80s.xml",
        "slug": "s80",
        "logo": "http://digital.100fm.co.il/app/images2/s80.png",
        "cover": "http://digital.100fm.co.il/app/cover/s80.png",
        "color": "#607d8b",
        "description": "יש לכם פוסטרים של סמנטה פוקס על הקיר,\nטייפ דאבל קסאט ואתם בדיוק עומדים לשבור את\nהשיא שלכם בפאקמן? זה הערוץ שלכם!\n100% 80’s כל ההימונונים הגדולים של שנות ה80."
    },
	{
        "name": "100% 70's",
        "audio": "http://gb25.streamgates.net/radios-audio/10070s/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/10070s/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch20-70s.xml",
        "slug": "s70",
        "logo": "http://digital.100fm.co.il/app/images2/s70.png",
        "cover": "http://digital.100fm.co.il/app/cover/s70.png",
        "color": "#607d8b",
        "description": "החיים שלכם דיסקו? מעריצים את סטיב אוסטין\nוחולמים על המלאכיות של צ'רלי? זה הערוץ\nשלכם. הלהיטים הגדולים של שנות ה70."
    },
	{
        "name": "100% No.1",
        "audio": "http://gb25.streamgates.net/radios-audio/100Number1/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Number1/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch8-Number1.xml",
        "slug": "no1",
        "logo": "http://digital.100fm.co.il/app/images2/no1.png",
        "cover": "http://digital.100fm.co.il/app/cover/no1.png",
        "color": "#8bc34a",
        "description": "מי זוכר את הסגן של בר כוכבא?! ווינרים\nבנשמה? – זה הערוץ שלכם!\nרק מקומות ראשונים הלהיטים שכבשו\nאת פסגת המצעדים."
    },
	{
        "name": "100% Oldies",
        "audio": "http://gb25.streamgates.net/radios-audio/100Oldies/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Oldies/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch3-Oldies.xml",
        "slug": "oldies",
        "logo": "http://digital.100fm.co.il/app/images2/oldies.png",
        "cover": "http://digital.100fm.co.il/app/cover/oldies.png",
        "color": "#9c27b0",
        "description": "אם אתם חושבים \"שפעם ידעו לעשות מוזיקה\"\nזה\nהערוץ שלכם! הלהיטים הנוסטלגיים\nשל שנות ה-60 בהשראת התוכנית\n\"Twlight Time\" בעריכת דוד בן בסט."
    },
	{
        "name": "100% Chillout",
        "audio": "http://gb25.streamgates.net/radios-audio/100Chillout/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Chillout/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch15-Chillout.xml",
        "slug": "chillout",
        "logo": "http://digital.100fm.co.il/app/images2/chillout.png",
        "cover": "http://digital.100fm.co.il/app/cover/chillout.png",
        "color": "#607d8b",
        "description": "הבוס הפיל עליכם חנות תיקים? הילדים\nלא הפסיקו לריב ולצרוח? קודם כל תרגעו ☺\nועכשיו תאזינו לערוץ – מוזיקה שתכניס\nאתכם לאווירה."
    },
	{
        "name": "100% World Music",
        "audio": "http://gb25.streamgates.net/radios-audio/100World/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100World/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch16-World.xml",
        "slug": "world",
        "logo": "http://digital.100fm.co.il/app/images2/world.png",
        "cover": "http://digital.100fm.co.il/app/cover/world.png",
        "color": "#607d8b",
        "description": "היה יום ארוך בעבודה? סיימתם אימון מקפיץ בחדר הכושר?\n\nאין כמו הרפיה בסוף היום, ואם אתם שם- זה בדיוק הערוץ בשבילכם!\n100% מוסיקת עולם מרגיעה לסיומו של היום"
    },
    {
        "name": "100% Club",
        "audio": "http://gb25.streamgates.net/radios-audio/100Club/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Club/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch11-Club.xml",
        "slug": "club",
        "logo": "http://digital.100fm.co.il/app/images2/club.png",
        "cover": "http://digital.100fm.co.il/app/cover/club.png",
        "color": "#795548",
        "description": "השכנים דופקים לכם בדלת כל שני וחמישי\nומבקשים להנמיך? – זה הערוץ שלכם!\nהטראקים הכי חמים בהשראת התוכנית\n\"Line Out\" עם דור דקל."
    },
	{
        "name": "100% Deep",
        "audio": "http://gb25.streamgates.net/radios-audio/100Deep/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Deep/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch22-Deep.xml",
        "slug": "deep",
        "logo": "http://digital.100fm.co.il/app/images2/deep.png",
        "cover": "http://digital.100fm.co.il/app/cover/deep,png",
        "color": "#607d8b",
        "description": "לא לוחצים על פליי בלי שנורקל ובלון חמצן? קחו\nאוויר אנחנו הולכים לצלול!\n100% Deep זה הערוץ שלכם."
    },
	{
        "name": "100% Trance",
        "audio": "http://gb25.streamgates.net/radios-audio/100Trance/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Trance/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch23-Trance.xml",
        "slug": "trance",
        "logo": "http://digital.100fm.co.il/app/images2/trance.png",
        "cover": "http://digital.100fm.co.il/app/cover/trance.png",
        "color": "#607d8b",
        "description": "אוהבים לחפור? עפים על החיים בקצב גבוה?\nזה הערוץ שלכם! כל הטראנסים הגדולים בעריכת\nשלומי קאופמן מגיש התוכנית \"Smash\"."
    },
	{
        "name": "100% DJSet",
        "audio": "http://gb25.streamgates.net/radios-audio/100Djset/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Djset/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch18-Djset.xml",
        "slug": "djset",
        "logo": "http://digital.100fm.co.il/app/images2/djset.png",
        "cover": "http://digital.100fm.co.il/app/cover/djset.png",
        "color": "#607d8b",
        "description": "לא יכולים לסבול הפסקות? מחפשים סיבה למסיבה ? זה הערוץ שלכם לא יכולים לסבול הפסקות? מחפשים סיבה\nלמסיבה? זה הערוץ שלכם!\nDJset Non Stop in the Mix\nכל הDJ’s המובילים בסטיים נונסטופ."
    },
	{
        "name": "100% Hiphop",
        "audio": "http://gb25.streamgates.net/radios-audio/100Hiphop/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Hiphop/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch10-Hiphop.xml",
        "slug": "hiphop",
        "logo": "http://digital.100fm.co.il/app/images2/hiphop.png",
        "cover": "http://digital.100fm.co.il/app/cover/hiphop.png",
        "color": "#ff5722",
        "description": "חולמים להיות עשירים כמו Kayne וכל\nמה שיש לכם זה 50 Cent? לא נורא\nבשביל זה יש לכם את הערוץ הזה!\nכל להיטי הHiphop בעריכת מומי לוי\nותוכניתו \"Base\"."
    },
    {
        "name": "100% Latin",
        "audio": "http://gb25.streamgates.net/radios-audio/100Latin/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Latin/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch12-Latin.xml",
        "slug": "latin",
        "logo": "http://digital.100fm.co.il/app/images2/latin.png",
        "cover": "http://digital.100fm.co.il/app/cover/latin.png",
        "color": "#9e9e9e",
        "description": "החיים שלכם טלנובלה? ר' מתגלגלת עושה\nלכם את זה? – זה הערוץ שלכם!\nהלהיטים הלטיניים הגדלוים מכל הזמנים\nבהשראת התוכניות \"חולם בספרדית\"\nו\"אהבה לטינית\" עם קיקה סמואל."
    },
	{
        "name": "100% Jazz",
        "audio": "http://gb25.streamgates.net/radios-audio/100Jazz/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Jazz/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch17-Jazz.xml",
        "slug": "jazz",
        "logo": "http://digital.100fm.co.il/app/images2/jazz.png",
        "cover": "http://digital.100fm.co.il/app/cover/jazz.png",
        "color": "#8bc34a",
        "description": "בא לכם סתם ככה באמצע היום לצלול לאווירת ג'אז מופלאה?\nזה הערוץ שלכם! \nמוסיקת ג'אז ללא הפסקה, ממש כמו במועדון אפלולי באווירה של חוץ לארץ"
    },
	{
        "name": "עושים היסטוריה",
        "audio": "http://gb25.streamgates.net/radios-audio/100History/playlist.m3u8",
		"audioA": "http://100history.streamgates.net:8162/autodj",
        "info": "http://100fm.xml.multix.co.il/xml/100history.xml",
        "slug": "history",
        "logo": "http://digital.100fm.co.il/img/history.png",
        "cover": "http://digital.100fm.co.il/img/history.png",
        "color": "#8bc34a",
        "description": "עושים היסטוריה עם רן לוי, הפודקאסט הכי פופולרי בישראל עכשיו בלעדי אצלנו ברדיוס 100FM",
		"sort":"1"
    },
	{
        "name": "100% Gamer",
        "audio": "http://gb25.streamgates.net/radios-audio/100Gamer/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Gamer/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/CH27-Gamer.xml",
        "slug": "Gamer",
        "logo": "http://digital.100fm.co.il/app/images2/gamer.png",
        "cover": "http://digital.100fm.co.il/app/cover/gamer.png",
        "color": "#607d8b",
        "description": "רדיוס מחשב, אקסבוקס, פלייסטיישן ונינטדו\nיש לנו כאן מהכל – כל הנעימות מהמשחקים\nהכי טובים שיש! בלעדי לרדיוס דיגיטל."
    },
	{
        "name": "100% Live",
        "audio": "http://gb25.streamgates.net/radios-audio/100Live/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Live/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch19-Live.xml",
        "slug": "live",
        "logo": "http://digital.100fm.co.il/app/images2/live.png",
        "cover": "http://digital.100fm.co.il/app/cover/live.png",
        "color": "#607d8b",
        "description": "מתים על חיות? חייבים להריח את הזיעה של ליידי\nגאגא מקרוב? סידרנו לכם כרטיס לשורה הראשונה\nשל הגולדן רינג עלינו!!\n100% לייב גירסאות מיוחדות של כל האומנים\nהגדולים."
    },
	{
        "name": "התקליטיה של",
        "audio": "http://gb25.streamgates.net/radios-audio/100Taklitia/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Taklitia/icecast.audio",
        "info": ">http://100fm.xml.multix.co.il/xml/100taklitia.xml",
        "slug": "taklitia",
        "logo": "http://digital.100fm.co.il/app/images2/taklitia.png",
        "cover": "http://digital.100fm.co.il/app/cover/taklitia.png",
        "color": "#607d8b",
        "description": "התקליטיה, המקום שבו האומנים בוחרים את השירים שהשפיעו עליהם הכי הרבה במהלך השנים"
    },
	{
        "name": "100% Movies",
        "audio": "http://gb25.streamgates.net/radios-audio/100Movies/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Movies/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch30-Movies.xml",
        "slug": "movies",
        "logo": "http://digital.100fm.co.il/app/images2/movies.png",
        "cover": "http://digital.100fm.co.il/app/cover/movies.png",
        "color": "#9c27b0",
        "description": "חיים ונושמים קולנוע? רוצים לשמוע מוסיקה מהסרטים? \nזה הערוץ שלכם! 100% Movies – כל השירים מכל הסרטים "
    },
	{
        "name": "100% Special",
        "audio": "http://gb25.streamgates.net/radios-audio/100Special/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Special/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch14-Special.xml",
        "slug": "special",
        "logo": "http://digital.100fm.co.il/app/images2/special.png",
        "cover": "http://digital.100fm.co.il/app/cover/special.png",
        "color": "#2196f3",
        "description": "חום יולי אוגוסט הגיע ואתם מזומנים לספיישל מרענן עם המיטב של שלמה ארצי."
    },
	{
        "name": "100% Rock",
        "audio": "http://gb25.streamgates.net/radios-audio/100Rock/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Rock/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch9-Rock.xml",
        "slug": "rock",
        "logo": "http://digital.100fm.co.il/app/images2/rock.png",
        "cover": "http://digital.100fm.co.il/app/cover/rock.png",
        "color": "#ffc107",
        "description": "אוכלים סיכות ביטחון לארוחת בוקר?\nBorn to be Wild? – זה הערוץ שלכם!\nלהיטי הרוק הגדולים מכל הזמנים."
    },
    {
        "name": "100% Café",
        "audio": "http://gb25.streamgates.net/radios-audio/100Cafe/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Cafe/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch26-Cafe.xml",
        "slug": "cafe",
        "logo": "http://digital.100fm.co.il/app/images2/cofe.png",
        "cover": "http://digital.100fm.co.il/app/cover/cafe.png",
        "color": "#607d8b",
        "description": "אז תשתה קפה טורקי ותתעורר אתה המשורר...\nתודו שאין כמו לקום בבוקר עם הקפה, מאפה\nושיר חדש בלב! 100% קפה פס הקול המושלם\nלפתוח איתו את הבוקר, צהריים וערב ☺"
    },
	{
        "name": "100% Hafla",
        "audio": "http://gb25.streamgates.net/radios-audio/91fm_digital_Hafla/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/91fm_digital_Hafla/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch91-Hafla.xml",
        "slug": "Hafla",
        "logo": "http://digital.100fm.co.il/app/images2/hafla.png",
        "cover": "http://digital.100fm.co.il/app/cover/hafla.png",
        "color": "#607d8b",
        "description": "רדיוס הסטקיים כבר על האש? היין בכוסות?\nתיידעו את כרמלה - אורחים נוספים הגיעו\nאייל גולן, ישי לוי, שרית חדד, משה פרץ\nוכל האומנים הגדולים בזמר הים תיכוני\nמחכים רק לכם ב100% חפלה\nהערוץ בשיתוף רדיו לב המדינה 91fm"
    },
	{
        "name": "100% Nostalgia",
        "audio": "http://gb25.streamgates.net/radios-audio/100Nostalgia/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Nostalgia/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch91-Nostalgia.xml",
        "slug": "Nostalgia",
        "logo": "http://digital.100fm.co.il/app/images2/nostalgia.png",
        "cover": "http://digital.100fm.co.il/app/cover/nostalgia.png",
        "color": "#795548",
        "description": "נוסטלגיה עברית באוויר.\nאם אתם במצברוח נוסטלגי ובא לכם קפיצה קטנה אל העבר, זה הערוץ שלכם!\n100% עברי נוסטלגי"
    },
	{
        "name": "100% Israeli",
        "audio": "http://gb25.streamgates.net/radios-audio/100Israeli/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Israeli/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch5-Israeli.xml",
        "slug": "israeli",
        "logo": "http://digital.100fm.co.il/app/images2/israeli.png",
        "cover": "http://digital.100fm.co.il/app/cover/israeli.png",
        "color": "#3f51b5",
        "description": "צופרים בשנייה שהרמזור מתחלף לצהוב?!\nאז זה הערוץ שמתאים לכם בול!\nהלהיטים הגדולים של מוסיקה הישראלית."
    },
	{
        "name": "100% Drivetime",
        "audio": "http://gb25.streamgates.net/radios-audio/100Drivetime/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Drivetime/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch25-Drivetime.xml",
        "slug": "drivetime",
        "logo": "http://digital.100fm.co.il/app/images2/drivetime.png",
        "cover": "http://digital.100fm.co.il/app/cover/drivetime.png",
        "color": "#607d8b",
        "description": "הדלקתם אורות? כיוונתם מראות? חגרתם\nחגורות? יופי! נשאר רק להתחבר לערוץ\nהדיגיטלי – 100% Drivetime מוסיקה\nשעושה קיצי באוזן כל הדרך הביתה\n(או אל הים)"
    },
	{
        "name": "100% Selfie",
        "audio": "http://gb25.streamgates.net/radios-audio/100Selfie/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Selfie/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch28-Selfie.xml",
        "slug": "Selfie",
        "logo": "http://digital.100fm.co.il/app/images2/selfie.png",
        "cover": "http://digital.100fm.co.il/app/cover/selfie.png",
        "color": "#607d8b",
        "description": "רדיוס עדי ביטי או נועה קירל? סטטיק או\nבן אל? למה לבחור? לנו יש את כולם!\n100% Selfie הלהיטים של כל כוכבי\nהנוער שהייתם רוצים לעשות איתם סלפי,\nהלו הלו...! אנחנו מדברים אליכם – תפסיקו\nלרגע לצלם את עצמכם :)"
    },
	{
        "name": "100% Love",
        "audio": "http://gb25.streamgates.net/radios-audio/100Love/playlist.m3u8",
		"audioA": "http://gb25.streamgates.net/radios-audio/100Love/icecast.audio",
        "info": "http://www.fmplayer.co.il/NowPlaying/Ch4-Love.xml",
        "slug": "love",
        "logo": "http://digital.100fm.co.il/app/images2/love.png",
        "cover": "http://digital.100fm.co.il/app/cover/love.png",
        "color": "#e91e63",
        "description": "מזגתם יין, הדלקתם נרות ופיזרתם עלי ורדים\nבכל מקום? (לא חראם על העוזרת?) – זה\nהערוץ שלכם! להיטי האהבה הגדולים מכל\nהזמנים בהשראת התוכנית \"אהבה פלוס\"\nעם ג'ני בלום."
}];